[database]
host = {{ env "MACRO_TERMINAL_DATABASE_HOST" }}
port = {{ env "MACRO_TERMINAL_DATABASE_PORT" }}
database = {{ env "MACRO_TERMINAL_DATABASE_NAME" }}
user = {{ env "MACRO_TERMINAL_DATABASE_USER" }}
password = {{ env "MACRO_TERMINAL_DATABASE_PASSWORD" }}
sslmode = {{ env "MACRO_TERMINAL_DATABASE_SSL_MODE" }}
version_table = public.schema_version
